Repository tyffical/Pridebot, pull requests merged in 2021-08, with the labels that each got.

#95 chore: Fix keep_alive and autodeploy scripts
  .replit
  main.py
  scripts/keep_alive.py
Labels: bug

#97 [fix] Hotword reaction🍉🦈🍉🦈
  main.py
Labels: bug

#98 feat: added custom reactions that needed nqn beforehand
  data/emojis.py
  main.py
Labels: enhancement

#101 Feat: Added Susblahaj Reacts
  data/emojis.py
  main.py
Labels: enhancement

#103 docs: Added Made with Python Badge and Discord Badge
  README.md
Labels: documentation

#104 feat: help cmd and many new reacts, fix: slash commands
  README.md
  cogs/utils.py
  data/emojis.py
  main.py
Labels: enhancement

#109 fix: Update README with correct oauth link
  README.md
Labels: bug

#107 feat: Create automated greeting when PRs are opened
  .github/workflows/greetings.yml
Labels: enhancement

#112 chore: installed gitpython package
  poetry.lock
  pyproject.toml
Labels: bug
